import { User, Project, Trade, Task, Photo, Comment } from '@/types';
import { v4 as uuidv4 } from 'uuid';

// Demo Users
export const demoUsers: User[] = [
    {
        id: 'user-client-1',
        email: 'mueller@email.de',
        name: 'Familie Müller',
        role: 'client',
        projectIds: ['project-1'],
        createdAt: new Date('2026-01-01'),
    },
    {
        id: 'user-architect-1',
        email: 'architekt@buero-schmidt.de',
        name: 'Thomas Schmidt',
        role: 'architect',
        avatarUrl: '/avatars/architect.jpg',
        createdAt: new Date('2025-06-01'),
    },
    {
        id: 'user-contractor-elektro',
        email: 'info@elektro-meier.de',
        name: 'Elektro Meier GmbH',
        role: 'contractor',
        assignedTradeIds: ['trade-elektro'],
        createdAt: new Date('2025-09-01'),
    },
    {
        id: 'user-contractor-sanitaer',
        email: 'info@sanitaer-weber.de',
        name: 'Sanitär Weber',
        role: 'contractor',
        assignedTradeIds: ['trade-sanitaer'],
        createdAt: new Date('2025-09-01'),
    },
];

// Demo Project with full structure
export const demoProject: Project = {
    id: 'project-1',
    name: 'Sanierung Villa Müller',
    address: 'Gartenstraße 15, 80331 München',
    clientId: 'user-client-1',
    clientName: 'Familie Müller',
    startDate: new Date('2026-01-15'),
    targetEndDate: new Date('2026-06-30'),
    status: 'active',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-29'),
    trades: [
        {
            id: 'trade-abbruch',
            projectId: 'project-1',
            name: 'Abbrucharbeiten',
            contractorId: 'user-contractor-abbruch',
            contractorName: 'Bau König GmbH',
            order: 1,
            tasks: [
                {
                    id: 'task-1',
                    tradeId: 'trade-abbruch',
                    title: 'Alte Fliesen entfernen',
                    status: 'done',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-15'),
                    updatedAt: new Date('2026-01-20'),
                },
                {
                    id: 'task-2',
                    tradeId: 'trade-abbruch',
                    title: 'Wände freilegen',
                    status: 'done',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-15'),
                    updatedAt: new Date('2026-01-22'),
                },
            ],
        },
        {
            id: 'trade-elektro',
            projectId: 'project-1',
            name: 'Elektroinstallation',
            contractorId: 'user-contractor-elektro',
            contractorName: 'Elektro Meier GmbH',
            order: 2,
            tasks: [
                {
                    id: 'task-3',
                    tradeId: 'trade-elektro',
                    title: 'Leitungen verlegen',
                    status: 'done',
                    photos: [
                        {
                            id: 'photo-1',
                            taskId: 'task-3',
                            fileUrl: '/demo/elektro-1.jpg',
                            thumbnailUrl: '/demo/elektro-1-thumb.jpg',
                            uploadedBy: 'user-contractor-elektro',
                            uploadedByName: 'Elektro Meier GmbH',
                            uploadedAt: new Date('2026-01-25'),
                            visibility: 'client',
                            caption: 'Leitungsführung Küche abgeschlossen',
                        },
                    ],
                    comments: [
                        {
                            id: 'comment-1',
                            taskId: 'task-3',
                            authorId: 'user-architect-1',
                            authorName: 'Thomas Schmidt',
                            authorRole: 'architect',
                            content: 'Saubere Arbeit, so kann es weitergehen!',
                            createdAt: new Date('2026-01-25'),
                            visibility: 'client',
                        },
                    ],
                    createdAt: new Date('2026-01-20'),
                    updatedAt: new Date('2026-01-25'),
                },
                {
                    id: 'task-4',
                    tradeId: 'trade-elektro',
                    title: 'Unterverteilung installieren',
                    status: 'in_progress',
                    photos: [
                        {
                            id: 'photo-2',
                            taskId: 'task-4',
                            fileUrl: '/demo/elektro-2.jpg',
                            thumbnailUrl: '/demo/elektro-2-thumb.jpg',
                            uploadedBy: 'user-contractor-elektro',
                            uploadedByName: 'Elektro Meier GmbH',
                            uploadedAt: new Date('2026-01-28'),
                            visibility: 'internal',
                            caption: 'Vorbereitung Unterverteilung',
                        },
                    ],
                    comments: [],
                    createdAt: new Date('2026-01-22'),
                    updatedAt: new Date('2026-01-28'),
                },
                {
                    id: 'task-5',
                    tradeId: 'trade-elektro',
                    title: 'Steckdosen setzen',
                    status: 'open',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-22'),
                    updatedAt: new Date('2026-01-22'),
                },
            ],
        },
        {
            id: 'trade-sanitaer',
            projectId: 'project-1',
            name: 'Sanitärinstallation',
            contractorId: 'user-contractor-sanitaer',
            contractorName: 'Sanitär Weber',
            order: 3,
            tasks: [
                {
                    id: 'task-6',
                    tradeId: 'trade-sanitaer',
                    title: 'Rohrleitungen verlegen',
                    status: 'in_progress',
                    photos: [],
                    comments: [
                        {
                            id: 'comment-2',
                            taskId: 'task-6',
                            authorId: 'user-contractor-sanitaer',
                            authorName: 'Sanitär Weber',
                            authorRole: 'contractor',
                            content: 'Material für Warmwasserleitungen verspätet - erwarte Lieferung morgen.',
                            createdAt: new Date('2026-01-28'),
                            visibility: 'internal',
                        },
                    ],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-28'),
                },
                {
                    id: 'task-7',
                    tradeId: 'trade-sanitaer',
                    title: 'Anschlüsse setzen',
                    status: 'blocked',
                    blockedReason: 'Warte auf Rohrleitungen',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-28'),
                },
                {
                    id: 'task-8',
                    tradeId: 'trade-sanitaer',
                    title: 'Armaturen montieren',
                    status: 'open',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-24'),
                },
            ],
        },
        {
            id: 'trade-trockenbau',
            projectId: 'project-1',
            name: 'Trockenbau',
            contractorId: 'user-contractor-trockenbau',
            contractorName: 'Innenausbau Krause',
            order: 4,
            tasks: [
                {
                    id: 'task-9',
                    tradeId: 'trade-trockenbau',
                    title: 'Ständerwerk errichten',
                    status: 'open',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-24'),
                },
                {
                    id: 'task-10',
                    tradeId: 'trade-trockenbau',
                    title: 'Gipskartonplatten montieren',
                    status: 'open',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-24'),
                },
            ],
        },
        {
            id: 'trade-maler',
            projectId: 'project-1',
            name: 'Malerarbeiten',
            order: 5,
            tasks: [
                {
                    id: 'task-11',
                    tradeId: 'trade-maler',
                    title: 'Streichen',
                    status: 'open',
                    photos: [],
                    comments: [],
                    createdAt: new Date('2026-01-24'),
                    updatedAt: new Date('2026-01-24'),
                },
            ],
        },
    ],
};

// Helper to get all projects (for demo, just one)
export const demoProjects: Project[] = [
    demoProject,
    // Second demo project
    {
        id: 'project-2',
        name: 'Büroumbau Schmidt GmbH',
        address: 'Industriestraße 42, 80939 München',
        clientId: 'user-client-2',
        clientName: 'Schmidt GmbH',
        startDate: new Date('2025-11-01'),
        targetEndDate: new Date('2026-03-15'),
        status: 'active',
        createdAt: new Date('2025-10-15'),
        updatedAt: new Date('2026-01-29'),
        trades: [
            {
                id: 'p2-trade-abbruch',
                projectId: 'project-2',
                name: 'Rückbau',
                contractorId: 'user-contractor-abbruch',
                contractorName: 'Bau König GmbH',
                order: 1,
                tasks: [
                    { id: 'p2-task-1', tradeId: 'p2-trade-abbruch', title: 'Alte Wände entfernen', status: 'done', photos: [], comments: [], createdAt: new Date('2025-11-05'), updatedAt: new Date('2025-11-15') },
                    { id: 'p2-task-2', tradeId: 'p2-trade-abbruch', title: 'Boden vorbereiten', status: 'done', photos: [], comments: [], createdAt: new Date('2025-11-05'), updatedAt: new Date('2025-11-20') },
                ],
            },
            {
                id: 'p2-trade-elektro',
                projectId: 'project-2',
                name: 'Elektroinstallation',
                contractorId: 'user-contractor-elektro',
                contractorName: 'Elektro Meier GmbH',
                order: 2,
                tasks: [
                    { id: 'p2-task-3', tradeId: 'p2-trade-elektro', title: 'Netzwerk-Verkabelung', status: 'done', photos: [], comments: [], createdAt: new Date('2025-12-01'), updatedAt: new Date('2026-01-10') },
                    { id: 'p2-task-4', tradeId: 'p2-trade-elektro', title: 'Beleuchtung installieren', status: 'done', photos: [], comments: [], createdAt: new Date('2025-12-01'), updatedAt: new Date('2026-01-15') },
                ],
            },
            {
                id: 'p2-trade-trockenbau',
                projectId: 'project-2',
                name: 'Trockenbau',
                contractorId: 'user-contractor-trockenbau',
                contractorName: 'Innenausbau Krause',
                order: 3,
                tasks: [
                    { id: 'p2-task-5', tradeId: 'p2-trade-trockenbau', title: 'Bürotrennwände', status: 'done', photos: [], comments: [], createdAt: new Date('2025-12-15'), updatedAt: new Date('2026-01-20') },
                    { id: 'p2-task-6', tradeId: 'p2-trade-trockenbau', title: 'Deckenverkleidung', status: 'in_progress', photos: [], comments: [], createdAt: new Date('2025-12-15'), updatedAt: new Date('2026-01-28') },
                ],
            },
            {
                id: 'p2-trade-boden',
                projectId: 'project-2',
                name: 'Bodenbelag',
                order: 4,
                tasks: [
                    { id: 'p2-task-7', tradeId: 'p2-trade-boden', title: 'Estrich verlegen', status: 'done', photos: [], comments: [], createdAt: new Date('2026-01-05'), updatedAt: new Date('2026-01-25') },
                    { id: 'p2-task-8', tradeId: 'p2-trade-boden', title: 'Teppich verlegen', status: 'open', photos: [], comments: [], createdAt: new Date('2026-01-05'), updatedAt: new Date('2026-01-05') },
                ],
            },
            {
                id: 'p2-trade-maler',
                projectId: 'project-2',
                name: 'Malerarbeiten',
                order: 5,
                tasks: [
                    { id: 'p2-task-9', tradeId: 'p2-trade-maler', title: 'Wände streichen', status: 'open', photos: [], comments: [], createdAt: new Date('2026-01-20'), updatedAt: new Date('2026-01-20') },
                ],
            },
        ],
    },
];

// Helper function to generate unique IDs
export function generateId(): string {
    return uuidv4();
}
